# Generated by Django 5.2.3 on 2025-06-24 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='tipo_comprobante',
            field=models.CharField(choices=[('BOLETA', 'Boleta'), ('FACTURA', 'Factura'), ('NOTA_VENTA', 'Nota de Venta'), ('TICKET', 'Ticket'), ('COTIZACION', 'Cotización'), ('OTRO', 'Otro')], max_length=50, verbose_name='Tipo de Comprobante'),
        ),
    ]
