# Generated by Django 5.2.3 on 2025-06-25 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pedidos", "0002_alter_pedido_tipo_comprobante"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pedido",
            name="cliente_dni",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="pedido",
            name="direccion",
            field=models.TextField(blank=True, null=True),
        ),
    ]
